version: '3.8'

services:
  auth-db:
    image: postgres:13-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: parola_secreta
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    container_name: auth-service
    build:
      context: ./services/AuthentificationMicroservice
    ports:
      - "8081:8080"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: admin
      DB_PASSWORD: parola_secreta
      
  calendar-db:
    image: postgres:13-alpine
    container_name: calendar-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: parola_secreta
      POSTGRES_DB: calendar_db
    ports:
      - "5433:5432"
    volumes:
      - calendar_db_data:/var/lib/postgresql/data
      
  calendar-service:
    container_name: calendar-service
    build:
      context: ./services/CalendarMicroservice
    ports:
      - "8082:8080"
    depends_on:
      - calendar-db
    environment:
      DB_HOST: calendar-db
      DB_PORT: 5432
      DB_NAME: calendar_db
      DB_USER: admin
      DB_PASSWORD: parola_secreta
      
  task-db:
    image: postgres:13-alpine
    container_name: task-db
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: parola_secreta
      POSTGRES_DB: task_db
    ports:
      - "5434:5432"
    volumes:
      - task_db_data:/var/lib/postgresql/data
      
  task-service:
    container_name: task-service
    build:
      context: ./services/TaskManagerMicroservice 
    ports:
      - "8083:8080"
    depends_on:
      - task-db
    environment:
      DB_HOST: task-db
      DB_PORT: 5432
      DB_NAME: task_db
      DB_USER: admin
      DB_PASSWORD: parola_secreta
      
  gateway-service:
    container_name: gateway-service
    build:
      context: ./services/PlanningMicroservice 
    ports:
      - "8080:8080"
    depends_on:
      - auth-service 
      - calendar-service 

volumes:
  auth_db_data:
  calendar_db_data:
  task_db_data:
